import { notFound } from "next/navigation";
import { Send } from "lucide-react";
import { prisma } from "@/lib/db";
import PrintButton from "@/components/PrintButton";
import { shareHep } from "@/app/actions";
import { BackLink, Badge } from "@/components/ui";
import { fmtDate, ageGender } from "@/lib/format";

export const dynamic = "force-dynamic";

// F-17 — printable / shareable Home Exercise Program (same print pattern as Rx/referral).
export default async function HepPrintPage({ params }: { params: { id: string } }) {
  const [hep, clinic] = await Promise.all([
    prisma.homeExerciseProgram.findUnique({
      where: { id: params.id },
      include: { patient: true, createdBy: true, exercises: { orderBy: { sortOrder: "asc" } } },
    }),
    prisma.clinic.findFirst(),
  ]);
  if (!hep) notFound();
  const { patient } = hep;

  return (
    <div className="mx-auto max-w-3xl">
      <div className="no-print mb-4 flex items-center justify-between">
        <BackLink href={`/patients/${patient.id}/physio`}>← Back to physiotherapy</BackLink>
        <div className="flex items-center gap-2">
          {hep.sharedAt ? (
            <Badge className="bg-green-100 text-green-700">Shared {fmtDate(hep.sharedAt)}</Badge>
          ) : (
            <form action={shareHep}>
              <input type="hidden" name="id" value={hep.id} />
              <button className="btn-ghost btn-sm">
                <Send size={14} /> Share on WhatsApp
              </button>
            </form>
          )}
          <PrintButton label="Print HEP" />
        </div>
      </div>

      <div className="print-area rounded-xl border border-slate-200 bg-white p-8 shadow-card">
        {/* Letterhead */}
        <div className="flex items-start justify-between border-b-2 border-brand-600 pb-4">
          <div className="flex items-center gap-3">
            <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-brand-600 text-lg font-bold text-white">
              {clinic?.logoInitials}
            </span>
            <div>
              <h1 className="text-lg font-bold text-slate-900">{clinic?.name}</h1>
              <p className="text-xs text-slate-500">{clinic?.tagline}</p>
              <p className="text-xs text-slate-500">{clinic?.phone}</p>
            </div>
          </div>
          <div className="text-right text-xs text-slate-500">
            <p className="text-sm font-semibold text-slate-800">Home Exercise Program</p>
            {hep.createdBy && <p>{hep.createdBy.name}</p>}
            <p>{fmtDate(hep.createdAt)}</p>
          </div>
        </div>

        {/* Patient */}
        <div className="mt-4 grid grid-cols-3 gap-2 rounded-lg bg-slate-50 p-3 text-sm">
          <p><span className="text-slate-400">Patient:</span> <span className="font-medium">{patient.name}</span></p>
          <p><span className="text-slate-400">Age/Sex:</span> {ageGender(patient.age, patient.gender)}</p>
          <p><span className="text-slate-400">Program:</span> {hep.title}</p>
        </div>

        {/* Exercises */}
        <div className="mt-6 space-y-3">
          {hep.exercises.map((e, i) => (
            <div key={e.id} className="flex gap-3 border-b border-slate-100 pb-3">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand-50 text-sm font-semibold text-brand-700">
                {i + 1}
              </span>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-medium text-slate-800">{e.name}</p>
                {e.instructions && <p className="text-sm text-slate-600">{e.instructions}</p>}
                {(e.sets || e.reps || e.frequency) && (
                  <p className="mt-0.5 text-xs text-slate-500">
                    {[e.sets && `${e.sets} sets`, e.reps, e.frequency].filter(Boolean).join(" · ")}
                  </p>
                )}
              </div>
            </div>
          ))}
          {hep.exercises.length === 0 && <p className="text-sm text-slate-400">No exercises.</p>}
        </div>

        {hep.note && <div className="mt-5 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-800">{hep.note}</div>}

        <p className="mt-8 border-t border-slate-100 pt-3 text-[10px] text-slate-400">
          Perform as advised by your physiotherapist. Stop and contact {clinic?.name}
          {clinic?.phone ? ` (${clinic.phone})` : ""} if you experience sharp or worsening pain. Computer-generated by {clinic?.name}.
        </p>
      </div>
    </div>
  );
}
